export enum EnumBillType {
  // bills
  Ticket = "Ticket",
  TicketBuy = "Ticket Buy",
  TicketSale = "Ticket Sale",
  TicketOperation = "TicketOperation",
  TicketOperationBuy = "Ticket Operation Buy",
  TicketOperationSale = "Ticket Operation Sale",
  Visa = "Visa",
  VisaBuy = "Visa Buy",
  VisaSale = "Visa Sale",
  Group = "Group",
  GroupBuy = "Group Buy",
  GroupSale = "Group Sale",
  Hotel = "Hotel",
  HotelBuy = "Hotel Buy",
  HotelSale = "Hotel Sale",
  Insurance = "Insurance",
  InsuranceBuy = "Insurance Buy",
  InsuranceSale = "Insurance Sale",
  Transport = "Transport",
  TransportBuy = "Transport Buy",
  TransportSale = "Transport Sale",
  // voucher
  Payment = "Payment",
  Receipt = "Receipt",
  ConstCard = "Const Card",
  Expenses = "Expenses",
  Exchange = "Exchange",
  ExchangeFrom = "Exchange From",
  ExchangeTo = "Exchange To",
  ExternalProfit = "External Profit",
  InitialBalance = "Initial Balance",
}
